# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    bandsintown.client:
        class: AppBundle\Client\BandsInTownClient
        arguments: ["@guzzle.client.bandsintown_api", "%bandsintown_api_id%"]

    artist.view_count.listener:
        class: AppBundle\EventListener\ArtistViewCountListener
        arguments: ["@request_stack"]
        tags:
            - { name: "kernel.event_listener", event: "app.artist.show", method: "onShow" }

    artist.subscriber:
        class: AppBundle\EventListener\ArtistEventSubscriber
        tags:
            - { name: "kernel.event_subscriber" }

    artist.voter:
        class: AppBundle\Security\ArtistVoter
        tags:
            - { name: security.voter }
        public: false
